# Generated by Django 4.2.4 on 2023-08-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommend_count',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
